# -*- mode: python -*-
#Illinois Open Source License
#
#University of Illinois
#Open Source License
#
#Copyright © 2014,    Board of Trustees of the University of Illinois.  All rights reserved.
#
#Developed by:
#
# Distributed Protocols Research Group in the Department of Computer Science
# The University of Illinois at Urbana-Champaign
# http:#dprg.cs.uiuc.edu/
# This is for the Project <Project Name here>. The paper can be found at the website http:#dprg.cs.uiuc.edu
#Mainak Ghosh, mghosh4@illinois.edu
#Wenting Wang, wwang84@illinois.edu
#Gopalakrishna Holla, vgkholla@gmail.com
#Indranil Gupta, indy@cs.uiuc.edu
#
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the “Software”), to deal with the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
#
#    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimers.
#    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimers in the documentation and/or other materials provided with the distribution.
#    * Neither the names of The Distributed Protocols Research Group (DPRG) or The University of Illinois at Urbana-Champaign, nor the names of its contributors may be used to endorse or promote products derived from this Software without specific prior written permission.
#
#THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
#PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
#AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.


Import("env")

stop_word_lanages = [
    'danish',
    'dutch',
    'english',
    'finnish',
    'french',
    'german',
    'hungarian',
    'italian',
    'norwegian',
    'portuguese',
    'romanian',
    'russian',
    'spanish',
    'swedish',
    'turkish',
]

env.Command( [ "stop_words_list.h", "stop_words_list.cpp"],
             [ "generate_stop_words.py"] + [ 'stop_words_%s.txt' % x for x in stop_word_lanages ],
             "$PYTHON $SOURCES $TARGETS" )

env.StaticLibrary('base', [
        'fts_index_format.cpp',
        'fts_matcher.cpp',
        'fts_query.cpp',
        'fts_spec.cpp',
        'fts_util.cpp',
        'stemmer.cpp',
        'stop_words.cpp',
        'stop_words_list.cpp',
        'tokenizer.cpp',
        ], LIBDEPS=["$BUILD_DIR/mongo/base/base",
                    "$BUILD_DIR/mongo/bson",
                    "$BUILD_DIR/mongo/platform/platform",
                    "$BUILD_DIR/third_party/libstemmer_c/stemmer"
                    ])

env.StaticLibrary( 'server_common', [
                   'fts_command.cpp',
                   'fts_enabled.cpp'
                   ] )

env.StaticLibrary('ftsmongod', [
        'fts_command_mongod.cpp',
        'fts_index.cpp',
        'fts_search.cpp',
        ], LIBDEPS=["base","server_common"])


env.StaticLibrary('ftsmongos', [
        'fts_command_mongos.cpp',
        ], LIBDEPS=["server_common"])


#env.CppUnitTest( "fts_index_format_test", "fts_index_format_test.cpp",
#                 LIBDEPS=["base"] )

#env.CppUnitTest( "fts_stop_words_test", "stop_words_test.cpp",
#                 LIBDEPS=["base"] )

#env.CppUnitTest( "fts_stemmer_test", "stemmer_test.cpp",
#                 LIBDEPS=["base"] )

#env.CppUnitTest( "fts_tokenizer_test", "tokenizer_test.cpp",
#                 LIBDEPS=["base"] )

#env.CppUnitTest( "fts_query_test", "fts_query_test.cpp",
#                 LIBDEPS=["base"] )

#env.CppUnitTest( "fts_spec_test", "fts_spec_test.cpp",
#                 LIBDEPS=["base"] )

#env.CppUnitTest( "fts_matcher_test", "fts_matcher_test.cpp",
#                 LIBDEPS=["base"] )

#env.CppUnitTest( "fts_util_test", "fts_util_test.cpp",
#                 LIBDEPS=["base","$BUILD_DIR/mongo/mongohasher"] )
